name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Allow CI to write
    strategy:
      matrix:
        app: [minecraft]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner_id }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Compute image tag
        id: compute
        run: |
          image_tag="ghcr.io/${{ github.repository }}/apps/${{ matrix.app }}:latest"
          echo "image=$image_tag" >> "$GITHUB_OUTPUT"
      
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/${{ matrix.app }}
          push: true
          tags: ${{ steps.compute.outputs.image }}
